### ISSUE TITLE
Changing theme colour doesn't change menu 'hamburger' colour

### ISSUE THREAD

**Issue by sandissauka** [Voog/design-boulder#59]
Changing theme colour doesn't change menu 'hamburger' colour (mobile/pad view). Theme colour has been changed to green, but menu 'hamburger' is still yellow.

http://mezaparkaskola.voog.com/

![image](https://cloud.githubusercontent.com/assets/1651064/9864286/b337b31a-5b50-11e5-9e41-b2c7f8fcad6d.jpeg)

**Comment by kaspar-naaber** [comment]
Also it doesn't change the search icon (visible in mobile view) color. It was decided so to prevent turning these icons white and invisible. After checking this solution again we discovered that it's not the best one because they are the only yellow elements that won't update it's color (which is misleading and looks like a bug).

Our new solution will be:
- [ ] Make menu icon and search icon color changeable again.
- [ ] Add color-picker for the header top-bar.

This way we will give the control back to user and he/she can easily change the header top-bar color if the menu button and search icon become invisible due to the chosen color.

**Comment by sandissauka** [comment]
Excellent news https://media.giphy.com/media/LgwoVr7YgUkrC/giphy.gif
